### ISSUE TITLE
Module consumers should be able to specify the version they want to use

### ISSUE THREAD

**Issue by wayne-folkes** [aws-cloudformation/cfn-language-discussion#34] opened 2022-02-10 14:39 UTC
### Name of the resource

Other

### Resource name

Modules

### Description

I would like to be able to specify a version of module when using it. The current behavior is that a stack will always attempt to use the latest version of the module for operations. I would be useful to specify a version so that updates to the stack dont introduce undesirable changes. This would be similar to SAR applications where you can specify the version of the app you want to use

**Comment by muneebar** [comment] 2022-05-12 18:17
Thanks for bringing this to our attention. This feature request is a duplicate of [#33](https://github.com/aws-cloudformation/cfn-language-discussion/issues/33), I will close this issue and welcome you to follow [#33](https://github.com/aws-cloudformation/cfn-language-discussion/issues/33) for further updates.

**Closed by muneebar** 2022-05-12 18:17 UTC
Labels: modules feature request
